query KitFeedbackIssues($filters: KitFeedback_IssueFilters, $pagination: KitFeedback_Pagination!) {
	KitFeedback_issues(filters: $filters, pagination: $pagination) {
		nodes {
			...KitFeedback_issuePreview
		}
		next
	}
}
